import React, { useState } from 'react';
import { 
  Box, Cpu, Layers, Play, RotateCcw, ChevronRight, ChevronLeft, 
  Terminal, Sparkles, Code2, CheckCircle2, Zap, ArrowRight, ShieldCheck,
  AlertTriangle, HelpCircle, Check, X, GitCommit, GitPullRequest, Info
} from 'lucide-react';
import UltraModernCodeViewer from '../common/UltraModernCodeViewer';

/**
 * JavaConstructorsVisualizer
 * High-Yield Interactive Visualizer with Deep Explanations:
 * 1. 3 Types of Constructors (Default vs No-Args vs Parameterized)
 * 2. Constructor Chaining & Overloading (this() & super() Call Stack Animation)
 * 3. Object Creation (new) vs Initialization (Constructor) Lifecycle
 * 4. Constructor vs Method Master Comparison & Rules
 */
export default function JavaConstructorsVisualizer() {
  const [activeTab, setActiveTab] = useState('types'); // 'types' | 'chaining' | 'lifecycle' | 'rules'
  const [selectedType, setSelectedType] = useState('default');
  const [chainingStep, setChainingStep] = useState(0);
  const [lifecycleStep, setLifecycleStep] = useState(0);

  // 3 Constructor Types Data with Deep Explanations
  const constructorTypes = [
    {
      id: 'default',
      name: '1. Default Constructor',
      author: 'Java Compiler (Automatic)',
      badge: 'Compiler Injected',
      badgeColor: 'border-blue-500/40 text-blue-300 bg-blue-950/60',
      summary: 'Automatically generated by javac only when the programmer writes ZERO constructors.',
      deepExplanation: 'When Java compiles a class with no constructors, javac inserts a no-argument constructor with access modifier matching the class and an implicit super() call. Its sole job is to trigger parent initialization and leave instance variables at language defaults (0, null, false).',
      points: [
        'Modifier: Inherits the class visibility (e.g. public class -> public constructor).',
        'Parameters: Exactly 0 parameters.',
        'Body: Contains only 1 hidden statement: super();',
        'State Result: Numeric fields become 0, references become null, booleans become false.'
      ],
      code: `public class Test {
    int id;
    String name;

    // The Java Compiler automatically injects this invisible code:
    // public Test() {
    //     super(); // Calls Object class constructor
    // }

    public static void main(String[] args) {
        Test t = new Test(); // Calls compiler-generated default constructor
        System.out.println("id: " + t.id);     // Output: 0
        System.out.println("name: " + t.name); // Output: null
    }
}`,
      output: `id: 0\nname: null`,
      memory: {
        constructorCall: 'Test() [Injected by Compiler]',
        fields: [
          { name: 'id', val: '0 (JVM Default)', color: 'text-slate-400' },
          { name: 'name', val: 'null (JVM Default)', color: 'text-slate-400' }
        ]
      }
    },
    {
      id: 'no-args',
      name: '2. No-Args Constructor',
      author: 'Programmer (Explicit 0 Params)',
      badge: 'Programmer Defined',
      badgeColor: 'border-amber-500/40 text-amber-300 bg-amber-950/60',
      summary: 'Written explicitly by the developer to provide standard default application state.',
      deepExplanation: 'Unlike the compiler-generated default constructor, an explicit No-Args constructor is crafted by the developer. It gives you full control over initial state, logging, resource acquisition, and default configuration without requiring constructor parameters.',
      points: [
        'Overrides the compiler default constructor completely.',
        'Allows assigning deliberate fallback values (e.g., name = "Deepak", status = "ACTIVE").',
        'Essential for frameworks like Spring, Hibernate, and Jackson for reflection instantiation.',
        'Can execute validation or trigger setup methods.'
      ],
      code: `public class Student {
    String name;
    String status;

    // Explicit No-Argument Constructor by Programmer
    public Student() {
        this.name = "Deepak";      // Custom initial state
        this.status = "ENROLLED";  // Default business status
    }

    void display() {
        System.out.println("Name: " + name + " | Status: " + status);
    }

    public static void main(String[] args) {
        Student s1 = new Student(); // Calls explicit no-arg constructor
        s1.display();
    }
}`,
      output: `Name: Deepak | Status: ENROLLED`,
      memory: {
        constructorCall: 'Student() [Explicit No-Args]',
        fields: [
          { name: 'name', val: '"Deepak" (Custom State)', color: 'text-cyan-300' },
          { name: 'status', val: '"ENROLLED"', color: 'text-amber-300' }
        ]
      }
    },
    {
      id: 'parameterized',
      name: '3. Parameterized Constructor',
      author: 'Programmer (With Arguments)',
      badge: 'Custom Arguments',
      badgeColor: 'border-emerald-500/40 text-emerald-300 bg-emerald-950/60',
      summary: 'Accepts arguments to initialize objects with distinct custom values at the instant of creation.',
      deepExplanation: 'Parameterized constructors enforce required fields during instantiation. Instead of creating an empty object and setting fields across 5 lines of setter code, the object is born in a valid, initialized state in a single atomic expression.',
      points: [
        'Accepts custom parameters: Student(String n, int rn) { ... }',
        'Guarantees that an object cannot exist in a half-initialized or invalid state.',
        'Enables immutable object design (when fields are marked final).',
        'Improves readability and eliminates boilerplate setter methods.'
      ],
      code: `public class Student {
    String name;
    int rollno;

    // Parameterized Constructor
    public Student(String name, int rollno) {
        this.name = name;     // 'this' distinguishes instance field from parameter
        this.rollno = rollno;
    }

    void display() {
        System.out.println("Name: " + name + ", Roll No.: " + rollno);
    }

    public static void main(String[] args) {
        Student s1 = new Student("Deepak", 101); // Passing distinct values
        s1.display();
    }
}`,
      output: `Name: Deepak, Roll No.: 101`,
      memory: {
        constructorCall: 'Student("Deepak", 101)',
        fields: [
          { name: 'name', val: '"Deepak"', color: 'text-emerald-300' },
          { name: 'rollno', val: '101', color: 'text-cyan-300' }
        ]
      }
    }
  ];

  // Constructor Chaining Animation Frames
  const chainingFrames = [
    {
      step: 1,
      title: "Step 1: Invocation of No-Args Constructor",
      badge: "Call Entry",
      code: "Student s = new Student();",
      callStack: ["main()", "Student()"],
      desc: "main() creates an object and calls the 0-arg constructor Student().",
      activeLine: 12,
      explanation: "The client code initiates creation using 'new Student()'. The JVM pushes the Student() frame onto the thread Call Stack."
    },
    {
      step: 2,
      title: "Step 2: Constructor Chaining via this(\"Guest\", 0)",
      badge: "this() Chaining",
      code: "this(\"Guest\", 0); // Jumps to Parameterized Constructor",
      callStack: ["main()", "Student()", "Student(String, int)"],
      desc: "Student() uses this(...) to delegate initialization to the 2-argument constructor.",
      activeLine: 3,
      explanation: "The this(...) call MUST be the very first line of the constructor. It prevents code duplication by routing all initialization logic through one master constructor."
    },
    {
      step: 3,
      title: "Step 3: Superclass Constructor Invocation (super())",
      badge: "super() Call",
      code: "super(); // Automatically calls java.lang.Object constructor",
      callStack: ["main()", "Student()", "Student(String, int)", "Object()"],
      desc: "Student(String, int) implicitly calls super() to initialize the root Object class metadata.",
      activeLine: 7,
      explanation: "Every constructor in Java must initialize its parent class first before setting its own fields. If no explicit super() or this() is provided, Java automatically calls super()."
    },
    {
      step: 4,
      title: "Step 4: Field Assignment & Stack Unwinding",
      badge: "Field Assignment",
      code: "this.name = \"Guest\"; this.rollno = 0;",
      callStack: ["main()"],
      desc: "Fields are assigned in the Heap object. Constructors return and frames are popped off the Call Stack.",
      activeLine: 8,
      explanation: "Object memory in the Heap is now populated: name='Guest', rollno=0. The reference address is assigned back to variable 's' in main()."
    }
  ];

  // Lifecycle Frames (new vs Constructor)
  const lifecycleFrames = [
    {
      step: 1,
      title: "Step 1: 'new' Operator Allocates Heap Memory (Creation Phase)",
      badge: "Creation Phase (RAM Allocation)",
      desc: "The 'new' keyword creates the object by allocating raw uninitialized bytes on the JVM Heap at memory address @0x8F3C.",
      deepWhy: "Constructors DO NOT allocate memory! The 'new' bytecode instruction (NEW in JVM opcode) allocates the heap structure. At this instant, fields contain only 0 and null.",
      heapState: {
        addr: "@0x8F3C",
        status: "Raw Uninitialized Byte Allocation",
        fields: [
          { key: "name", val: "null", note: "raw JVM default" },
          { key: "rollno", val: "0", note: "raw JVM default" }
        ]
      },
      constructorActive: false,
      stackRef: "s1 = null (not bound yet)"
    },
    {
      step: 2,
      title: "Step 2: Constructor Execution (Initialization Phase)",
      badge: "Initialization Phase",
      desc: "The constructor Student(\"Deepak\", 101) executes. It calls super() and assigns values to instance variables.",
      deepWhy: "The constructor (INVOKESPECIAL <init> in bytecode) runs to transform the raw memory block into a valid domain object by setting business values.",
      heapState: {
        addr: "@0x8F3C",
        status: "Constructor Initializing Fields",
        fields: [
          { key: "name", val: '"Deepak"', note: "assigned via constructor" },
          { key: "rollno", val: "101", note: "assigned via constructor" }
        ]
      },
      constructorActive: true,
      stackRef: "s1 = null (waiting for completion)"
    },
    {
      step: 3,
      title: "Step 3: Reference Pointer Binding (Completion Phase)",
      badge: "Completion Phase",
      desc: "The Heap memory address (@0x8F3C) is assigned to the Stack reference variable 's1'. Object is fully live!",
      deepWhy: "The assignment operator (=) completes the link. Variable 's1' on the stack now holds the address @0x8F3C and can invoke methods.",
      heapState: {
        addr: "@0x8F3C",
        status: "Object Fully Initialized & Live in Heap",
        fields: [
          { key: "name", val: '"Deepak"', note: "ready" },
          { key: "rollno", val: "101", note: "ready" }
        ]
      },
      constructorActive: false,
      stackRef: "s1 = @0x8F3C ────► [Heap Object]"
    }
  ];

  // Rules validator items
  const rulesList = [
    {
      rule: "1. Same Name as Class",
      valid: true,
      desc: "The constructor name must exactly match the enclosing class name (case-sensitive).",
      example: "class Student { public Student() { ... } }",
      why: "Ensures the JVM compiler can unambiguously distinguish object initialization from arbitrary method calls."
    },
    {
      rule: "2. No Return Type (Not even void)",
      valid: true,
      desc: "Constructors never have a return type. If you write 'void Student()', it is treated as a regular method!",
      example: "public void Student() { ... } ⚠️ Warning: Treated as regular method, NOT constructor!",
      why: "The constructor's implicit purpose is to initialize and return the instance created by 'new'."
    },
    {
      rule: "3. Allowed Access Modifiers",
      valid: true,
      desc: "Can be public, protected, default (package-private), or private.",
      example: "private Student() { ... } // Used in Singleton Pattern to block 'new' from outside!",
      why: "Controls who is permitted to instantiate objects of this class."
    },
    {
      rule: "4. Disallowed Non-Access Modifiers",
      valid: false,
      desc: "Cannot have static, final, abstract, synchronized, native, or strictfp.",
      example: "public static Student() ❌ Compiler Error: Modifier static not allowed here",
      why: "Constructors belong exclusively to newly allocated Heap object instances, not to the static Class metadata."
    },
    {
      rule: "5. Automatic Invocation via 'new'",
      valid: true,
      desc: "Whenever 'new ClassName()' executes, exactly one matching constructor is invoked.",
      example: "Student s = new Student(); // Constructor triggers immediately",
      why: "Guarantees no object enters the application without passing through initialization logic."
    }
  ];

  const currentTypeData = constructorTypes.find(t => t.id === selectedType) || constructorTypes[0];
  const currentChainingFrame = chainingFrames[chainingStep];
  const currentLifecycleFrame = lifecycleFrames[lifecycleStep];

  return (
    <div className="rounded-3xl border border-cyan-500/40 bg-gradient-to-b from-[#091122] via-[#070D1A] to-[#040812] p-6 sm:p-8 shadow-2xl space-y-6 relative overflow-hidden">
      
      {/* Background ambient lighting */}
      <div className="absolute top-0 right-1/4 w-96 h-96 bg-cyan-500/10 rounded-full blur-3xl pointer-events-none" />
      <div className="absolute bottom-0 left-1/4 w-96 h-96 bg-amber-500/10 rounded-full blur-3xl pointer-events-none" />

      {/* Header */}
      <div className="flex flex-wrap items-center justify-between gap-4 pb-4 border-b border-slate-800 relative z-10">
        <div>
          <div className="flex items-center gap-2 text-xs font-mono font-bold text-cyan-400 uppercase tracking-wider">
            <Zap className="w-4 h-4 text-cyan-400 animate-pulse" />
            <span>Interactive Object Initialization Theater</span>
          </div>
          <h3 className="text-xl sm:text-2xl font-extrabold text-white tracking-tight">
            Constructors in Java
          </h3>
        </div>

        {/* Master Tab Selector */}
        <div className="flex flex-wrap items-center gap-1.5 p-1 rounded-2xl bg-slate-900/90 border border-slate-800">
          <button
            onClick={() => setActiveTab('types')}
            className={`px-3.5 py-1.5 rounded-xl text-xs font-bold transition flex items-center gap-1.5 ${
              activeTab === 'types'
                ? 'bg-cyan-500 text-slate-950 shadow-md shadow-cyan-500/30'
                : 'text-slate-400 hover:text-slate-200'
            }`}
          >
            <Box className="w-3.5 h-3.5" />
            <span>3 Types of Constructors</span>
          </button>

          <button
            onClick={() => setActiveTab('chaining')}
            className={`px-3.5 py-1.5 rounded-xl text-xs font-bold transition flex items-center gap-1.5 ${
              activeTab === 'chaining'
                ? 'bg-cyan-500 text-slate-950 shadow-md shadow-cyan-500/30'
                : 'text-slate-400 hover:text-slate-200'
            }`}
          >
            <GitPullRequest className="w-3.5 h-3.5" />
            <span>Chaining & this()</span>
          </button>

          <button
            onClick={() => setActiveTab('lifecycle')}
            className={`px-3.5 py-1.5 rounded-xl text-xs font-bold transition flex items-center gap-1.5 ${
              activeTab === 'lifecycle'
                ? 'bg-cyan-500 text-slate-950 shadow-md shadow-cyan-500/30'
                : 'text-slate-400 hover:text-slate-200'
            }`}
          >
            <Cpu className="w-3.5 h-3.5" />
            <span>Creation vs Initialization</span>
          </button>

          <button
            onClick={() => setActiveTab('rules')}
            className={`px-3.5 py-1.5 rounded-xl text-xs font-bold transition flex items-center gap-1.5 ${
              activeTab === 'rules'
                ? 'bg-cyan-500 text-slate-950 shadow-md shadow-cyan-500/30'
                : 'text-slate-400 hover:text-slate-200'
            }`}
          >
            <ShieldCheck className="w-3.5 h-3.5" />
            <span>Rules & Modifiers</span>
          </button>
        </div>
      </div>

      {/* ===================================================================== */}
      {/* TAB 1: 3 CONSTRUCTOR TYPES (Default, No-Args, Parameterized)          */}
      {/* ===================================================================== */}
      {activeTab === 'types' && (
        <div className="space-y-6 relative z-10">
          
          {/* 3 Selector Cards */}
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
            {constructorTypes.map(type => {
              const isSelected = selectedType === type.id;
              return (
                <button
                  key={type.id}
                  onClick={() => setSelectedType(type.id)}
                  className={`p-4 rounded-2xl border text-left transition-all duration-200 space-y-1.5 ${
                    isSelected
                      ? 'bg-slate-800/90 border-cyan-500 shadow-lg shadow-cyan-500/20 scale-[1.02]'
                      : 'bg-slate-900/60 border-slate-800/80 hover:bg-slate-800/50 hover:border-slate-700'
                  }`}
                >
                  <div className="flex items-center justify-between">
                    <span className="text-xs font-bold text-white tracking-tight">{type.name}</span>
                    <span className={`text-[10px] font-mono font-bold px-2 py-0.5 rounded-full border ${type.badgeColor}`}>
                      {type.badge}
                    </span>
                  </div>
                  <span className="text-[11px] text-slate-400 block line-clamp-1">{type.author}</span>
                </button>
              );
            })}
          </div>

          {/* Active Constructor Deep Dive View */}
          <div className="grid grid-cols-1 xl:grid-cols-12 gap-6 items-start">
            
            {/* Left: Code Viewer & Output (6 cols) */}
            <div className="xl:col-span-6 space-y-4 min-w-0">
              <div className="space-y-2">
                <div className="flex items-center justify-between pb-1 text-xs text-slate-400 font-mono">
                  <span className="text-cyan-300 font-bold flex items-center gap-1.5">
                    <Code2 className="w-3.5 h-3.5" />
                    <span>{currentTypeData.name} Implementation</span>
                  </span>
                  <span>Java 21</span>
                </div>
                <UltraModernCodeViewer code={currentTypeData.code} />
              </div>

              {/* Console Output */}
              <div className="rounded-2xl bg-[#040711] border border-slate-800 p-4 space-y-2 font-mono text-xs shadow-inner">
                <div className="flex items-center justify-between text-slate-400 border-b border-slate-800 pb-1 text-[11px]">
                  <span className="flex items-center gap-1 text-emerald-400 font-bold">
                    <Terminal className="w-3.5 h-3.5" />
                    <span>Console Output</span>
                  </span>
                  <span>Exit 0</span>
                </div>
                <pre className="text-emerald-300 leading-relaxed whitespace-pre-line">
                  {currentTypeData.output}
                </pre>
              </div>
            </div>

            {/* Right: Explanation & JVM Heap Memory Snapshot (6 cols) */}
            <div className="xl:col-span-6 space-y-4 min-w-0">
              
              {/* Summary Box */}
              <div className="p-5 rounded-2xl bg-[#060B16] border border-slate-800 space-y-3 shadow-inner">
                <div className="flex items-center justify-between">
                  <span className={`text-xs font-mono font-bold px-2.5 py-1 rounded-full border ${currentTypeData.badgeColor}`}>
                    {currentTypeData.badge}
                  </span>
                  <span className="text-xs font-mono text-slate-500">Deep Theory Breakdown</span>
                </div>

                <h4 className="text-base font-bold text-white leading-snug">
                  {currentTypeData.summary}
                </h4>

                <p className="text-xs text-slate-300 leading-relaxed bg-slate-900/60 p-3 rounded-xl border border-slate-800/80">
                  {currentTypeData.deepExplanation}
                </p>

                <ul className="space-y-1.5 text-xs text-slate-300 pt-1">
                  {currentTypeData.points.map((item, idx) => (
                    <li key={idx} className="flex items-start gap-2">
                      <span className="text-cyan-400 font-bold shrink-0">✓</span>
                      <span className="leading-relaxed">{item}</span>
                    </li>
                  ))}
                </ul>
              </div>

              {/* Memory Heap Object Representation */}
              <div className="p-5 rounded-2xl bg-[#061413] border border-emerald-500/40 space-y-3 shadow-inner font-mono text-xs">
                <div className="flex items-center justify-between pb-2 border-b border-emerald-900/60">
                  <span className="text-emerald-400 font-bold flex items-center gap-1.5">
                    <Cpu className="w-4 h-4" />
                    <span>JVM Heap Memory Result</span>
                  </span>
                  <span className="text-[10px] text-amber-300 bg-slate-900 px-2 py-0.5 rounded border border-slate-800">
                    {currentTypeData.memory.constructorCall}
                  </span>
                </div>

                <div className="space-y-1.5 text-slate-300">
                  <span className="text-[11px] text-slate-400 block mb-1">Initialized Object State in Heap:</span>
                  {currentTypeData.memory.fields.map((f, idx) => (
                    <div key={idx} className="flex justify-between p-2 rounded-lg bg-slate-950/80 border border-slate-800">
                      <span className="text-slate-400">{f.name}:</span>
                      <span className={`font-bold ${f.color}`}>{f.val}</span>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* ===================================================================== */}
      {/* TAB 2: CONSTRUCTOR CHAINING & OVERLOADING (this() & super())          */}
      {/* ===================================================================== */}
      {activeTab === 'chaining' && (
        <div className="space-y-6 relative z-10">
          
          <div className="p-4 sm:p-5 rounded-2xl bg-slate-900/90 border border-slate-800 space-y-1.5">
            <h4 className="text-sm sm:text-base font-bold text-white flex items-center gap-2">
              <GitPullRequest className="w-4 h-4 text-cyan-400" />
              <span>What is Constructor Chaining in Java?</span>
            </h4>
            <p className="text-xs sm:text-sm text-slate-300 leading-relaxed">
              <strong>Constructor Chaining</strong> is the process of calling one constructor from another constructor within the same class (using <code>this()</code>) or from the subclass to superclass (using <code>super()</code>). This eliminates duplicate initialization logic!
            </p>
          </div>

          {/* Stepper Header Bar */}
          <div className="p-4 rounded-2xl bg-slate-900/90 border border-slate-800 flex flex-wrap items-center justify-between gap-4">
            <div className="space-y-0.5">
              <span className="text-[11px] font-mono font-bold text-cyan-400 uppercase">
                {currentChainingFrame.badge}
              </span>
              <h4 className="text-sm sm:text-base font-bold text-white">
                {currentChainingFrame.title}
              </h4>
              <p className="text-xs text-slate-300 max-w-xl">
                {currentChainingFrame.desc}
              </p>
            </div>

            <div className="flex items-center gap-2">
              <button
                onClick={() => setChainingStep(Math.max(0, chainingStep - 1))}
                disabled={chainingStep === 0}
                className="p-1.5 rounded-xl bg-slate-800 hover:bg-slate-700 disabled:opacity-30 text-slate-300 transition"
              >
                <ChevronLeft className="w-4 h-4" />
              </button>

              <span className="text-xs font-mono text-cyan-300 font-bold px-2">
                Step {chainingStep + 1} of {chainingFrames.length}
              </span>

              <button
                onClick={() => setChainingStep(Math.min(chainingFrames.length - 1, chainingStep + 1))}
                disabled={chainingStep === chainingFrames.length - 1}
                className="p-1.5 rounded-xl bg-slate-800 hover:bg-slate-700 disabled:opacity-30 text-slate-300 transition"
              >
                <ChevronRight className="w-4 h-4" />
              </button>

              <button
                onClick={() => setChainingStep(0)}
                className="p-1.5 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-400 transition"
              >
                <RotateCcw className="w-4 h-4" />
              </button>
            </div>
          </div>

          {/* Stepper Visualization: Left Java Code + Right Call Stack & Explanation */}
          <div className="grid grid-cols-1 xl:grid-cols-12 gap-6 items-start">
            
            {/* Left: Code Box (6 cols) */}
            <div className="xl:col-span-6 rounded-2xl bg-[#040711] border border-slate-800 p-4 font-mono text-xs shadow-inner">
              <div className="text-[11px] text-slate-400 pb-2 border-b border-slate-800 mb-2">
                <span>Constructor Chaining Code (Student.java)</span>
              </div>
              <div className="space-y-1 text-slate-300 text-[11.5px]">
                <div className="text-slate-500">1: class Student {'{'}</div>
                <div className="text-slate-500">2:     String name; int rollno;</div>
                <div className={`p-1 rounded ${chainingStep === 1 ? 'bg-cyan-500/20 text-cyan-300 font-bold border border-cyan-500/40' : ''}`}>
                  3:     Student() {'{'} this("Guest", 0); {'}'} // Calls overloaded
                </div>
                <div className="text-slate-500">4:</div>
                <div className="text-slate-500">5:     Student(String name, int rollno) {'{'}</div>
                <div className={`p-1 rounded ${chainingStep === 2 ? 'bg-amber-500/20 text-amber-300 font-bold border border-amber-500/40' : ''}`}>
                  6:         super(); // Calls Object class
                </div>
                <div className={`p-1 rounded ${chainingStep === 3 ? 'bg-emerald-500/20 text-emerald-300 font-bold border border-emerald-500/40' : ''}`}>
                  7:         this.name = name; this.rollno = rollno;
                </div>
                <div className="text-slate-500">8:     {'}'}</div>
                <div className="text-slate-500">9: {'}'}</div>
                <div className={`p-1 rounded mt-2 ${chainingStep === 0 ? 'bg-blue-500/20 text-blue-300 font-bold border border-blue-500/40' : ''}`}>
                  10: Student s = new Student(); // Triggers chain
                </div>
              </div>
            </div>

            {/* Right: Thread Call Stack Animation & Explanation (6 cols) */}
            <div className="xl:col-span-6 space-y-4">
              
              {/* JVM Call Stack */}
              <div className="p-5 rounded-2xl bg-[#060D1A] border border-cyan-500/30 font-mono text-xs space-y-3">
                <span className="text-cyan-400 font-bold block pb-1 border-b border-slate-800">
                  JVM Thread Call Stack (Top to Bottom):
                </span>
                <div className="space-y-1.5">
                  {currentChainingFrame.callStack.slice().reverse().map((frame, idx) => (
                    <div
                      key={idx}
                      className={`p-2.5 rounded-xl border flex items-center justify-between ${
                        idx === 0
                          ? 'bg-cyan-500/20 border-cyan-500 text-cyan-200 font-bold shadow-md'
                          : 'bg-slate-900 border-slate-800 text-slate-400'
                      }`}
                    >
                      <span>{frame}</span>
                      {idx === 0 && <span className="text-[10px] text-cyan-400 font-bold uppercase">Active Frame</span>}
                    </div>
                  ))}
                </div>
              </div>

              {/* Step Explanation Callout */}
              <div className="p-4 rounded-2xl bg-cyan-950/30 border border-cyan-800/40 text-xs text-cyan-200 space-y-1">
                <strong className="text-cyan-300 font-bold block flex items-center gap-1.5">
                  <Info className="w-3.5 h-3.5" />
                  <span>Why this happens:</span>
                </strong>
                <p className="leading-relaxed text-slate-300">
                  {currentChainingFrame.explanation}
                </p>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* ===================================================================== */}
      {/* TAB 3: OBJECT CREATION vs INITIALIZATION LIFECYCLE                    */}
      {/* ===================================================================== */}
      {activeTab === 'lifecycle' && (
        <div className="space-y-6 relative z-10">
          
          {/* Important Distinction Banner */}
          <div className="p-4 sm:p-5 rounded-2xl bg-cyan-950/40 border border-cyan-500/40 text-xs sm:text-sm text-cyan-200 flex items-start gap-3">
            <span className="text-xl shrink-0">💡</span>
            <div>
              <strong className="text-cyan-300 font-bold block mb-0.5">Crucial JVM Architectural Fact:</strong>
              <span>
                <strong>Constructors do NOT create objects!</strong> The <code>new</code> operator allocates physical RAM on the JVM Heap (Creation). The Constructor executes on that allocated block to assign initial state and invoke parent initializers (Initialization).
              </span>
            </div>
          </div>

          {/* Stepper Header Bar */}
          <div className="p-4 rounded-2xl bg-slate-900/90 border border-slate-800 flex flex-wrap items-center justify-between gap-4">
            <div className="space-y-0.5">
              <span className="text-[11px] font-mono font-bold text-cyan-400 uppercase">
                {currentLifecycleFrame.badge}
              </span>
              <h4 className="text-sm sm:text-base font-bold text-white">
                {currentLifecycleFrame.title}
              </h4>
              <p className="text-xs text-slate-300 max-w-xl">
                {currentLifecycleFrame.desc}
              </p>
            </div>

            <div className="flex items-center gap-2">
              <button
                onClick={() => setLifecycleStep(Math.max(0, lifecycleStep - 1))}
                disabled={lifecycleStep === 0}
                className="p-1.5 rounded-xl bg-slate-800 hover:bg-slate-700 disabled:opacity-30 text-slate-300 transition"
              >
                <ChevronLeft className="w-4 h-4" />
              </button>

              <span className="text-xs font-mono text-cyan-300 font-bold px-2">
                Step {lifecycleStep + 1} of {lifecycleFrames.length}
              </span>

              <button
                onClick={() => setLifecycleStep(Math.min(lifecycleFrames.length - 1, lifecycleStep + 1))}
                disabled={lifecycleStep === lifecycleFrames.length - 1}
                className="p-1.5 rounded-xl bg-slate-800 hover:bg-slate-700 disabled:opacity-30 text-slate-300 transition"
              >
                <ChevronRight className="w-4 h-4" />
              </button>

              <button
                onClick={() => setLifecycleStep(0)}
                className="p-1.5 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-400 transition"
              >
                <RotateCcw className="w-4 h-4" />
              </button>
            </div>
          </div>

          {/* Visual Lifecycle Comparison: Stack -> Constructor Engine -> Heap */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4 font-mono text-xs">
            
            {/* 1. Stack Reference */}
            <div className="p-5 rounded-2xl bg-[#060D1A] border border-cyan-500/30 space-y-3 shadow-inner">
              <span className="text-cyan-400 font-bold block pb-2 border-b border-slate-800">
                1. Stack Frame (main)
              </span>
              <div className="p-3 rounded-xl bg-slate-950 border border-slate-800 text-slate-300">
                <span className="text-slate-400 block text-[10px]">Reference Variable:</span>
                <strong className="text-cyan-300">{currentLifecycleFrame.stackRef}</strong>
              </div>
            </div>

            {/* 2. Constructor Engine */}
            <div className={`p-5 rounded-2xl border space-y-3 shadow-inner transition-all duration-300 ${
              currentLifecycleFrame.constructorActive
                ? 'bg-amber-950/40 border-amber-500/60 shadow-lg shadow-amber-500/10'
                : 'bg-[#040711] border-slate-800'
            }`}>
              <div className="flex items-center justify-between pb-2 border-b border-slate-800">
                <span className="text-amber-400 font-bold">2. Constructor Engine</span>
                {currentLifecycleFrame.constructorActive && (
                  <span className="w-2 h-2 rounded-full bg-amber-400 animate-ping" />
                )}
              </div>
              <div className="p-3 rounded-xl bg-slate-950 border border-slate-800 text-slate-300 space-y-1">
                <div className="text-[11px] text-amber-300">Student(String, int)</div>
                <div className="text-[10px] text-slate-400">1. Invokes super()</div>
                <div className="text-[10px] text-slate-400">2. Initializes fields</div>
              </div>
            </div>

            {/* 3. Heap Memory */}
            <div className="p-5 rounded-2xl bg-[#061413] border border-emerald-500/40 space-y-3 shadow-inner">
              <div className="flex items-center justify-between pb-2 border-b border-emerald-900/60">
                <span className="text-emerald-400 font-bold">3. Heap Memory</span>
                <span className="text-[10px] text-amber-300">{currentLifecycleFrame.heapState.addr}</span>
              </div>
              <div className="p-3 rounded-xl bg-slate-950 border border-slate-800 space-y-1.5">
                <span className="text-[10px] text-slate-500 block">{currentLifecycleFrame.heapState.status}</span>
                {currentLifecycleFrame.heapState.fields.map((f, idx) => (
                  <div key={idx} className="flex justify-between text-[11px]">
                    <span className="text-slate-400">{f.key}:</span>
                    <span className="text-emerald-300 font-bold">{f.val}</span>
                  </div>
                ))}
              </div>
            </div>
          </div>

          {/* Deep Why Callout */}
          <div className="p-4 rounded-2xl bg-slate-900/80 border border-slate-800 text-xs text-slate-300 space-y-1">
            <strong className="text-cyan-300 font-bold block flex items-center gap-1.5">
              <Info className="w-3.5 h-3.5" />
              <span>Under the Hood (JVM Bytecode Instruction):</span>
            </strong>
            <p className="leading-relaxed">
              {currentLifecycleFrame.deepWhy}
            </p>
          </div>
        </div>
      )}

      {/* ===================================================================== */}
      {/* TAB 4: RULES & MODIFIERS COMPLIANCE MATRIX                            */}
      {/* ===================================================================== */}
      {activeTab === 'rules' && (
        <div className="space-y-5 relative z-10">
          
          <div className="p-4 rounded-2xl bg-slate-900/80 border border-slate-800 text-xs sm:text-sm text-slate-300 leading-relaxed">
            Java enforces strict compiler rules for constructor naming, return types, and access modifiers. Review the breakdown below:
          </div>

          <div className="space-y-3">
            {rulesList.map((item, idx) => (
              <div
                key={idx}
                className="p-4 sm:p-5 rounded-2xl bg-[#060B16] border border-slate-800 hover:border-slate-700 transition space-y-2"
              >
                <div className="flex items-center justify-between">
                  <h4 className="text-xs sm:text-sm font-bold text-white flex items-center gap-2">
                    {item.valid ? (
                      <Check className="w-4 h-4 text-emerald-400 shrink-0" />
                    ) : (
                      <X className="w-4 h-4 text-rose-400 shrink-0" />
                    )}
                    <span>{item.rule}</span>
                  </h4>
                  <span className={`text-[10px] font-mono font-bold px-2 py-0.5 rounded-full ${
                    item.valid ? 'bg-emerald-950 text-emerald-300 border border-emerald-800' : 'bg-rose-950 text-rose-300 border border-rose-800'
                  }`}>
                    {item.valid ? 'Allowed / Required' : 'Disallowed'}
                  </span>
                </div>

                <p className="text-xs text-slate-300 leading-relaxed">
                  {item.desc}
                </p>

                <div className="p-2.5 rounded-xl bg-slate-950 border border-slate-800 font-mono text-[11.5px] text-cyan-300">
                  {item.example}
                </div>

                <div className="text-[11px] text-slate-400 pt-1 flex items-start gap-1.5">
                  <strong className="text-slate-300 font-bold shrink-0">Rationale:</strong>
                  <span>{item.why}</span>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
