import React, { useState, useEffect } from 'react';
import { 
  Box, Cpu, Layers, Play, RotateCcw, ChevronRight, ChevronLeft, 
  Terminal, Sparkles, Code2, CheckCircle2, Zap, ArrowRight, Folder,
  FolderOpen, FileCode, Check, Server, Share2, Layers2, ShieldCheck,
  GitBranch, ArrowDown, Network, Lock, FileText, CheckCircle
} from 'lucide-react';
import UltraModernCodeViewer from '../common/UltraModernCodeViewer';

/**
 * JavaPackagesVisualizer
 * High-Yield Interactive Java Packages Simulator (100% Dynamic Code Animation):
 * 1. Interactive Cross-Package Import Bridge & ClassLoader Pipeline
 * 2. Namespace Collision Resolver (java.util.Date vs java.sql.Date)
 * 3. Built-in vs User-Defined Package Explorer
 * 4. Interactive Terminal CLI Step-by-Step Compilation & Run Simulator
 */
export default function JavaPackagesVisualizer() {
  const [activeTab, setActiveTab] = useState('bridge'); // 'bridge' | 'collision' | 'types' | 'cli'
  const [bridgeStep, setBridgeStep] = useState(0);
  const [isBridgePlaying, setIsBridgePlaying] = useState(false);
  const [cliStep, setCliStep] = useState(0);
  const [selectedPkgType, setSelectedPkgType] = useState('user'); // 'builtin' | 'user'

  // Cross-package import animation steps
  const bridgeSteps = [
    {
      step: 1,
      title: "Step 1: Declaration of Package p1 (p1/MyClass.java)",
      badge: "Package Scoping",
      desc: "MyClass is declared inside 'package p1;'. Its public methods become available for export.",
      activeNode: "p1",
      importActive: false,
      callout: "The package statement places MyClass in the p1 namespace and inside folder './p1'."
    },
    {
      step: 2,
      title: "Step 2: Consumer Imports Package (import p1.MyClass)",
      badge: "Import Bridge Activated",
      desc: "p2/MainApp.java declares 'import p1.MyClass;'. The Java compiler establishes a namespace bridge.",
      activeNode: "bridge",
      importActive: true,
      callout: "Importing does NOT copy bytecode! It simply instructs the compiler and JVM where to find the type."
    },
    {
      step: 3,
      title: "Step 3: ClassLoader Resolves & Executes (obj.display())",
      badge: "Execution Complete",
      desc: "JVM loads p1/MyClass.class from classpath and executes display(). Output: 'Hello from MyClass in p1 package.'",
      activeNode: "p2",
      importActive: true,
      callout: "Cross-package execution succeeded with zero naming conflicts and clean modular boundaries."
    }
  ];

  // Terminal CLI Steps
  const cliSteps = [
    {
      step: 1,
      command: "javac p1/MyClass.java",
      title: "Step 1: Compile the Package Class (p1.MyClass)",
      badge: "javac Compilation",
      desc: "Compiles MyClass.java inside the p1 directory into bytecode: p1/MyClass.class",
      terminalOutput: "$ javac p1/MyClass.java\n[INFO] Generated bytecode: p1/MyClass.class",
      fsState: [
        { name: "p1/MyClass.java", type: "java" },
        { name: "p1/MyClass.class", type: "class", highlight: true },
        { name: "p2/MainApp.java", type: "java" }
      ]
    },
    {
      step: 2,
      command: "javac -cp . p2/MainApp.java",
      title: "Step 2: Compile the Consumer Class (p2.MainApp)",
      badge: "Classpath Resolution",
      desc: "Compiles MainApp.java using the current directory ('.') as the classpath so javac can locate p1.MyClass.",
      terminalOutput: "$ javac -cp . p2/MainApp.java\n[INFO] Resolved import p1.MyClass from classpath '.'\n[INFO] Generated bytecode: p2/MainApp.class",
      fsState: [
        { name: "p1/MyClass.java", type: "java" },
        { name: "p1/MyClass.class", type: "class" },
        { name: "p2/MainApp.java", type: "java" },
        { name: "p2/MainApp.class", type: "class", highlight: true }
      ]
    },
    {
      step: 3,
      command: "java p2.MainApp",
      title: "Step 3: Execute via Fully Qualified Name",
      badge: "JVM Execution",
      desc: "The JVM loads p2.MainApp, loads its dependency p1.MyClass from classpath, and triggers main().",
      terminalOutput: "$ java p2.MainApp\nHello from MyClass in p1 package.\n[Process finished with exit code 0]",
      fsState: [
        { name: "p1/MyClass.java", type: "java" },
        { name: "p1/MyClass.class", type: "class" },
        { name: "p2/MainApp.java", type: "java" },
        { name: "p2/MainApp.class", type: "class" }
      ]
    }
  ];

  // Auto-play for bridge
  useEffect(() => {
    let timer;
    if (isBridgePlaying) {
      timer = setInterval(() => {
        setBridgeStep(prev => (prev < bridgeSteps.length - 1 ? prev + 1 : 0));
      }, 2500);
    }
    return () => clearInterval(timer);
  }, [isBridgePlaying]);

  const codeP1 = `package p1;

public class MyClass {
    public void display() {
        System.out.println("Hello from MyClass in p1 package.");
    }
}`;

  const codeP2 = `package p2;

import p1.MyClass; // Importing MyClass from p1 package

public class MainApp {
    public static void main(String[] args) {
        MyClass obj = new MyClass();
        obj.display();
    }
}`;

  const codeBuiltin = `import java.util.Scanner;

public class MainApp {
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        System.out.print("Enter your name: ");
        String name = sc.nextLine();
        System.out.println("Hello, " + name);
    }
}`;

  const codeCollision = `// Resolving identical class names using Packages:
import java.util.Date; // Standard utility timestamp

public class DateConflictDemo {
    public static void main(String[] args) {
        // 1. Using imported java.util.Date
        Date utilDate = new Date();
        System.out.println("Util Date: " + utilDate);

        // 2. Using Fully Qualified Name for java.sql.Date
        java.sql.Date sqlDate = new java.sql.Date(System.currentTimeMillis());
        System.out.println("SQL Date: " + sqlDate);
    }
}`;

  const currentBridge = bridgeSteps[bridgeStep];
  const currentCli = cliSteps[cliStep];

  return (
    <div className="rounded-3xl border border-cyan-500/40 bg-gradient-to-b from-[#091122] via-[#070D1A] to-[#040812] p-6 sm:p-8 shadow-2xl space-y-6 relative overflow-hidden">
      
      {/* Background ambient lighting */}
      <div className="absolute top-0 right-1/4 w-96 h-96 bg-cyan-500/10 rounded-full blur-3xl pointer-events-none" />
      <div className="absolute bottom-0 left-1/4 w-96 h-96 bg-blue-500/10 rounded-full blur-3xl pointer-events-none" />

      {/* Header */}
      <div className="flex flex-wrap items-center justify-between gap-4 pb-4 border-b border-slate-800 relative z-10">
        <div>
          <div className="flex items-center gap-2 text-xs font-mono font-bold text-cyan-400 uppercase tracking-wider">
            <Zap className="w-4 h-4 text-cyan-400 animate-pulse" />
            <span>Interactive Namespace & Package Theater</span>
          </div>
          <h3 className="text-xl sm:text-2xl font-extrabold text-white tracking-tight">
            Packages in Java
          </h3>
        </div>

        {/* Master Tab Selector */}
        <div className="flex flex-wrap items-center gap-1.5 p-1 rounded-2xl bg-slate-900/90 border border-slate-800">
          <button
            onClick={() => setActiveTab('bridge')}
            className={`px-3.5 py-1.5 rounded-xl text-xs font-bold transition flex items-center gap-1.5 ${
              activeTab === 'bridge'
                ? 'bg-cyan-500 text-slate-950 shadow-md shadow-cyan-500/30'
                : 'text-slate-400 hover:text-slate-200'
            }`}
          >
            <Network className="w-3.5 h-3.5" />
            <span>Import Bridge Animation</span>
          </button>

          <button
            onClick={() => setActiveTab('collision')}
            className={`px-3.5 py-1.5 rounded-xl text-xs font-bold transition flex items-center gap-1.5 ${
              activeTab === 'collision'
                ? 'bg-cyan-500 text-slate-950 shadow-md shadow-cyan-500/30'
                : 'text-slate-400 hover:text-slate-200'
            }`}
          >
            <ShieldCheck className="w-3.5 h-3.5" />
            <span>Namespace Conflict Resolver</span>
          </button>

          <button
            onClick={() => setActiveTab('types')}
            className={`px-3.5 py-1.5 rounded-xl text-xs font-bold transition flex items-center gap-1.5 ${
              activeTab === 'types'
                ? 'bg-cyan-500 text-slate-950 shadow-md shadow-cyan-500/30'
                : 'text-slate-400 hover:text-slate-200'
            }`}
          >
            <Folder className="w-3.5 h-3.5" />
            <span>Built-in vs User-Defined</span>
          </button>

          <button
            onClick={() => setActiveTab('cli')}
            className={`px-3.5 py-1.5 rounded-xl text-xs font-bold transition flex items-center gap-1.5 ${
              activeTab === 'cli'
                ? 'bg-cyan-500 text-slate-950 shadow-md shadow-cyan-500/30'
                : 'text-slate-400 hover:text-slate-200'
            }`}
          >
            <Terminal className="w-3.5 h-3.5" />
            <span>Terminal CLI Compilation</span>
          </button>
        </div>
      </div>

      {/* ===================================================================== */}
      {/* TAB 1: DYNAMIC IMPORT BRIDGE ANIMATION                                */}
      {/* ===================================================================== */}
      {activeTab === 'bridge' && (
        <div className="space-y-6 relative z-10">
          
          <div className="p-4 sm:p-5 rounded-2xl bg-slate-900/90 border border-slate-800 space-y-1.5">
            <h4 className="text-sm sm:text-base font-bold text-white flex items-center gap-2">
              <Network className="w-4 h-4 text-cyan-400" />
              <span>Cross-Package Import Bridge Pipeline</span>
            </h4>
            <p className="text-xs sm:text-sm text-slate-300 leading-relaxed">
              Watch how <code>package p2</code> imports and consumes <code>MyClass</code> from <code>package p1</code> across directory folders in real time.
            </p>
          </div>

          {/* Stepper Header Bar */}
          <div className="p-4 rounded-2xl bg-slate-900/90 border border-slate-800 flex flex-wrap items-center justify-between gap-4">
            <div className="space-y-0.5">
              <span className="text-[11px] font-mono font-bold text-cyan-400 uppercase">
                {currentBridge.badge}
              </span>
              <h4 className="text-sm sm:text-base font-bold text-white">
                {currentBridge.title}
              </h4>
              <p className="text-xs text-slate-300 max-w-xl">
                {currentBridge.desc}
              </p>
            </div>

            <div className="flex items-center gap-2">
              <button
                onClick={() => setIsBridgePlaying(!isBridgePlaying)}
                className={`px-3 py-1.5 rounded-xl text-xs font-mono font-bold flex items-center gap-1.5 transition ${
                  isBridgePlaying ? 'bg-amber-500 text-slate-950' : 'bg-cyan-500 text-slate-950'
                }`}
              >
                <Play className="w-3.5 h-3.5" />
                <span>{isBridgePlaying ? 'Pause' : 'Auto Play'}</span>
              </button>

              <button
                onClick={() => setBridgeStep(Math.max(0, bridgeStep - 1))}
                disabled={bridgeStep === 0}
                className="p-1.5 rounded-xl bg-slate-800 hover:bg-slate-700 disabled:opacity-30 text-slate-300 transition"
              >
                <ChevronLeft className="w-4 h-4" />
              </button>

              <span className="text-xs font-mono text-cyan-300 font-bold px-2">
                Step {bridgeStep + 1} of {bridgeSteps.length}
              </span>

              <button
                onClick={() => setBridgeStep(Math.min(bridgeSteps.length - 1, bridgeStep + 1))}
                disabled={bridgeStep === bridgeSteps.length - 1}
                className="p-1.5 rounded-xl bg-slate-800 hover:bg-slate-700 disabled:opacity-30 text-slate-300 transition"
              >
                <ChevronRight className="w-4 h-4" />
              </button>

              <button
                onClick={() => setBridgeStep(0)}
                className="p-1.5 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-400 transition"
              >
                <RotateCcw className="w-4 h-4" />
              </button>
            </div>
          </div>

          {/* Dynamic 2-Node Visualizer with Data Packet Animation */}
          <div className="p-6 rounded-2xl bg-[#060B16] border border-cyan-500/40 space-y-6 shadow-inner font-mono text-xs">
            <span className="text-[10px] text-slate-500 uppercase font-bold tracking-wider block text-center">
              Active Namespace Bridge: p1 ➔ p2
            </span>

            <div className="grid grid-cols-1 md:grid-cols-12 gap-4 items-center">
              
              {/* Package p1 Node (5 cols) */}
              <div className={`md:col-span-5 p-5 rounded-2xl border space-y-3 transition-all duration-300 ${
                currentBridge.activeNode === 'p1' || currentBridge.activeNode === 'bridge'
                  ? 'bg-blue-950/60 border-blue-500 shadow-lg shadow-blue-500/20 scale-[1.02]'
                  : 'bg-slate-950 border-slate-800 opacity-70'
              }`}>
                <div className="flex items-center justify-between pb-2 border-b border-blue-900/60">
                  <span className="text-blue-400 font-bold flex items-center gap-2">
                    <Folder className="w-4 h-4" />
                    <span>package p1;</span>
                  </span>
                  <span className="text-[10px] text-blue-300 bg-blue-900/60 px-2 py-0.5 rounded border border-blue-700">
                    Source Folder: ./p1
                  </span>
                </div>

                <div className="p-3 rounded-xl bg-slate-900 border border-slate-800 text-slate-300 space-y-1">
                  <div className="flex items-center gap-2 text-cyan-300 font-bold">
                    <FileCode className="w-4 h-4" />
                    <span>MyClass.java</span>
                  </div>
                  <div className="text-[11px] text-slate-400 pl-6">
                    • public void display()
                  </div>
                </div>
              </div>

              {/* Animated Bridge Connector (2 cols) */}
              <div className="md:col-span-2 flex flex-col items-center justify-center gap-1 text-center py-2">
                <span className={`text-[10px] font-bold px-2 py-1 rounded-full border transition-all ${
                  currentBridge.importActive
                    ? 'bg-emerald-950 text-emerald-300 border-emerald-500 animate-pulse shadow-md shadow-emerald-500/30'
                    : 'bg-slate-900 text-slate-600 border-slate-800'
                }`}>
                  import p1.MyClass;
                </span>
                <div className="w-full flex items-center justify-center text-cyan-400 font-bold">
                  {currentBridge.importActive ? (
                    <span className="animate-bounce text-sm">──────►</span>
                  ) : (
                    <span className="text-slate-700">───────</span>
                  )}
                </div>
                <span className="text-[9px] text-slate-500">Classpath Linking</span>
              </div>

              {/* Package p2 Node (5 cols) */}
              <div className={`md:col-span-5 p-5 rounded-2xl border space-y-3 transition-all duration-300 ${
                currentBridge.activeNode === 'p2' || currentBridge.activeNode === 'bridge'
                  ? 'bg-emerald-950/60 border-emerald-500 shadow-lg shadow-emerald-500/20 scale-[1.02]'
                  : 'bg-slate-950 border-slate-800 opacity-70'
              }`}>
                <div className="flex items-center justify-between pb-2 border-b border-emerald-900/60">
                  <span className="text-emerald-400 font-bold flex items-center gap-2">
                    <Folder className="w-4 h-4" />
                    <span>package p2;</span>
                  </span>
                  <span className="text-[10px] text-emerald-300 bg-emerald-900/60 px-2 py-0.5 rounded border border-emerald-700">
                    Consumer Folder: ./p2
                  </span>
                </div>

                <div className="p-3 rounded-xl bg-slate-900 border border-slate-800 text-slate-300 space-y-1">
                  <div className="flex items-center gap-2 text-emerald-300 font-bold">
                    <FileCode className="w-4 h-4" />
                    <span>MainApp.java</span>
                  </div>
                  <div className="text-[11px] text-slate-400 pl-6">
                    • MyClass obj = new MyClass();
                    <br />
                    • obj.display();
                  </div>
                </div>
              </div>
            </div>

            {/* Step Insight */}
            <div className="p-3.5 rounded-xl bg-slate-950 border border-slate-800 text-cyan-300 flex items-center justify-between text-xs">
              <span>Execution Insight:</span>
              <strong className="text-white">{currentBridge.callout}</strong>
            </div>
          </div>
        </div>
      )}

      {/* ===================================================================== */}
      {/* TAB 2: NAMESPACE COLLISION RESOLVER                                   */}
      {/* ===================================================================== */}
      {activeTab === 'collision' && (
        <div className="space-y-6 relative z-10">
          
          <div className="p-4 sm:p-5 rounded-2xl bg-slate-900/90 border border-slate-800 space-y-1.5">
            <h4 className="text-sm sm:text-base font-bold text-white flex items-center gap-2">
              <ShieldCheck className="w-4 h-4 text-emerald-400" />
              <span>Solving Name Collisions with Fully Qualified Names</span>
            </h4>
            <p className="text-xs sm:text-sm text-slate-300 leading-relaxed">
              What happens when two different libraries provide a class with the exact same name (e.g. <code>Date</code> in <code>java.util</code> and <code>java.sql</code>)? Packages resolve this cleanly through <strong>Fully Qualified Class Names</strong>!
            </p>
          </div>

          <div className="grid grid-cols-1 xl:grid-cols-12 gap-6 items-start">
            <div className="xl:col-span-7 space-y-2 min-w-0">
              <div className="flex items-center justify-between pb-1 text-xs text-slate-400 font-mono">
                <span className="text-cyan-300 font-bold flex items-center gap-1.5">
                  <Code2 className="w-3.5 h-3.5" />
                  <span>Collision Resolution Program</span>
                </span>
                <span>Java 21</span>
              </div>
              <UltraModernCodeViewer code={codeCollision} />
            </div>

            <div className="xl:col-span-5 space-y-4 min-w-0">
              <div className="p-5 rounded-2xl bg-[#060B16] border border-slate-800 space-y-3 font-mono text-xs">
                <span className="text-cyan-400 font-bold text-sm block border-b border-slate-800 pb-2">
                  Collision Resolution Rules:
                </span>
                <div className="space-y-2 text-slate-300 text-xs">
                  <div className="p-2.5 rounded-xl bg-slate-950 border border-slate-800">
                    <strong className="text-blue-300 block mb-0.5">1. Import Priority:</strong>
                    <span><code>import java.util.Date;</code> allows referring to <code>Date</code> directly.</span>
                  </div>
                  <div className="p-2.5 rounded-xl bg-slate-950 border border-slate-800">
                    <strong className="text-amber-300 block mb-0.5">2. Fully Qualified Syntax:</strong>
                    <span><code>java.sql.Date sqlDate = ...</code> disambiguates the second Date class with zero conflict.</span>
                  </div>
                </div>
              </div>

              <div className="p-4 rounded-2xl bg-[#040711] border border-slate-800 font-mono text-xs shadow-inner space-y-2">
                <div className="flex items-center justify-between text-slate-400 border-b border-slate-800 pb-1 text-[11px]">
                  <span className="flex items-center gap-1 text-emerald-400 font-bold">
                    <Terminal className="w-3.5 h-3.5" />
                    <span>Console Output</span>
                  </span>
                  <span>Exit 0</span>
                </div>
                <pre className="text-emerald-300 leading-relaxed whitespace-pre-line">
                  Util Date: Sat Aug 29 11:51:00 UTC 2026{'\n'}SQL Date: 2026-08-29
                </pre>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* ===================================================================== */}
      {/* TAB 3: BUILT-IN VS USER-DEFINED PACKAGES                              */}
      {/* ===================================================================== */}
      {activeTab === 'types' && (
        <div className="space-y-6 relative z-10">
          
          {/* Switcher Buttons */}
          <div className="flex items-center gap-3">
            <button
              onClick={() => setSelectedPkgType('builtin')}
              className={`px-4 py-2 rounded-xl text-xs font-bold transition ${
                selectedPkgType === 'builtin'
                  ? 'bg-cyan-500 text-slate-950 shadow-md shadow-cyan-500/30'
                  : 'bg-slate-900 text-slate-400 hover:text-white border border-slate-800'
              }`}
            >
              1. Built-in Packages (java.util, java.lang, java.io)
            </button>

            <button
              onClick={() => setSelectedPkgType('user')}
              className={`px-4 py-2 rounded-xl text-xs font-bold transition ${
                selectedPkgType === 'user'
                  ? 'bg-cyan-500 text-slate-950 shadow-md shadow-cyan-500/30'
                  : 'bg-slate-900 text-slate-400 hover:text-white border border-slate-800'
              }`}
            >
              2. User-Defined Packages (package p1 & p2)
            </button>
          </div>

          {/* Active View */}
          {selectedPkgType === 'builtin' ? (
            <div className="grid grid-cols-1 xl:grid-cols-12 gap-6 items-start">
              <div className="xl:col-span-7 space-y-2 min-w-0">
                <div className="flex items-center justify-between pb-1 text-xs text-slate-400 font-mono">
                  <span className="text-cyan-300 font-bold flex items-center gap-1.5">
                    <Code2 className="w-3.5 h-3.5" />
                    <span>Built-in Package Example (java.util.Scanner)</span>
                  </span>
                  <span>Java 21</span>
                </div>
                <UltraModernCodeViewer code={codeBuiltin} />
              </div>

              <div className="xl:col-span-5 space-y-4 min-w-0">
                <div className="p-5 rounded-2xl bg-[#060B16] border border-slate-800 space-y-3 font-mono text-xs">
                  <span className="text-cyan-400 font-bold text-sm block border-b border-slate-800 pb-2">
                    Common Built-in Packages
                  </span>
                  <div className="space-y-2 text-slate-300">
                    <div className="p-2 rounded-lg bg-slate-950 border border-slate-800">
                      <strong className="text-white block">java.lang</strong>
                      <span className="text-slate-400 text-[11px]">Automatically imported; contains String, Math, Object, Thread, System.</span>
                    </div>
                    <div className="p-2 rounded-lg bg-slate-950 border border-slate-800">
                      <strong className="text-white block">java.util</strong>
                      <span className="text-slate-400 text-[11px]">Collections Framework, Scanner, Date, UUID, Optional.</span>
                    </div>
                    <div className="p-2 rounded-lg bg-slate-950 border border-slate-800">
                      <strong className="text-white block">java.io / java.nio</strong>
                      <span className="text-slate-400 text-[11px]">Input/Output file streams, buffers, readers, writers.</span>
                    </div>
                  </div>
                </div>

                <div className="p-4 rounded-2xl bg-[#040711] border border-slate-800 font-mono text-xs shadow-inner space-y-2">
                  <div className="flex items-center justify-between text-slate-400 border-b border-slate-800 pb-1 text-[11px]">
                    <span className="flex items-center gap-1 text-emerald-400 font-bold">
                      <Terminal className="w-3.5 h-3.5" />
                      <span>Console Output</span>
                    </span>
                    <span>Exit 0</span>
                  </div>
                  <pre className="text-emerald-300 leading-relaxed whitespace-pre-line">
                    Enter your name: Deepak{'\n'}Hello, Deepak
                  </pre>
                </div>
              </div>
            </div>
          ) : (
            <div className="grid grid-cols-1 md:grid-cols-2 gap-5 items-start">
              <div className="space-y-2">
                <div className="p-3 rounded-xl bg-blue-950/30 border border-blue-500/40 text-xs">
                  <strong className="text-blue-300 block font-bold mb-0.5">Package p1 (p1/MyClass.java)</strong>
                  <span className="text-slate-300 text-[11px]">Defines reusable <code>MyClass</code> inside <code>package p1;</code></span>
                </div>
                <UltraModernCodeViewer code={codeP1} />
              </div>

              <div className="space-y-2">
                <div className="p-3 rounded-xl bg-emerald-950/30 border border-emerald-500/40 text-xs">
                  <strong className="text-emerald-300 block font-bold mb-0.5">Package p2 (p2/MainApp.java)</strong>
                  <span className="text-slate-300 text-[11px]">Imports <code>import p1.MyClass;</code> and consumes it</span>
                </div>
                <UltraModernCodeViewer code={codeP2} />
              </div>
            </div>
          )}
        </div>
      )}

      {/* ===================================================================== */}
      {/* TAB 4: TERMINAL CLI STEPPER                                           */}
      {/* ===================================================================== */}
      {activeTab === 'cli' && (
        <div className="space-y-6 relative z-10">
          
          {/* Stepper Header Bar */}
          <div className="p-4 rounded-2xl bg-slate-900/90 border border-slate-800 flex flex-wrap items-center justify-between gap-4">
            <div className="space-y-0.5">
              <span className="text-[11px] font-mono font-bold text-cyan-400 uppercase">
                {currentCli.badge}
              </span>
              <h4 className="text-sm sm:text-base font-bold text-white">
                {currentCli.title}
              </h4>
              <p className="text-xs text-slate-300 max-w-xl">
                {currentCli.desc}
              </p>
            </div>

            <div className="flex items-center gap-2">
              <button
                onClick={() => setCliStep(Math.max(0, cliStep - 1))}
                disabled={cliStep === 0}
                className="p-1.5 rounded-xl bg-slate-800 hover:bg-slate-700 disabled:opacity-30 text-slate-300 transition"
              >
                <ChevronLeft className="w-4 h-4" />
              </button>

              <span className="text-xs font-mono text-cyan-300 font-bold px-2">
                Step {cliStep + 1} of {cliSteps.length}
              </span>

              <button
                onClick={() => setCliStep(Math.min(cliSteps.length - 1, cliStep + 1))}
                disabled={cliStep === cliSteps.length - 1}
                className="p-1.5 rounded-xl bg-slate-800 hover:bg-slate-700 disabled:opacity-30 text-slate-300 transition"
              >
                <ChevronRight className="w-4 h-4" />
              </button>

              <button
                onClick={() => setCliStep(0)}
                className="p-1.5 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-400 transition"
              >
                <RotateCcw className="w-4 h-4" />
              </button>
            </div>
          </div>

          {/* Architecture Split: Terminal Console on Left + File Tree on Right */}
          <div className="grid grid-cols-1 md:grid-cols-12 gap-5 font-mono text-xs">
            
            {/* Terminal Console (7 cols) */}
            <div className="md:col-span-7 p-5 rounded-2xl bg-[#040711] border border-slate-800 shadow-inner space-y-3">
              <div className="flex items-center justify-between pb-2 border-b border-slate-800 text-slate-400 text-[11px]">
                <span className="flex items-center gap-1.5 text-cyan-400 font-bold">
                  <Terminal className="w-4 h-4" />
                  <span>Terminal Bash / PowerShell</span>
                </span>
                <span>Active Command: <strong className="text-white">{currentCli.command}</strong></span>
              </div>

              <pre className="text-cyan-300 leading-relaxed whitespace-pre-line text-xs">
                {currentCli.terminalOutput}
              </pre>
            </div>

            {/* Disk File System View (5 cols) */}
            <div className="md:col-span-5 p-5 rounded-2xl bg-[#060D1A] border border-cyan-500/40 shadow-inner space-y-3">
              <span className="text-cyan-400 font-bold block pb-1 border-b border-slate-800">
                Operating System File Tree:
              </span>

              <div className="space-y-1.5 text-slate-300">
                {currentCli.fsState.map((file, idx) => (
                  <div
                    key={idx}
                    className={`p-2 rounded-lg border flex items-center justify-between ${
                      file.highlight
                        ? 'bg-cyan-500/20 border-cyan-500 text-cyan-200 font-bold shadow-md'
                        : 'bg-slate-950 border-slate-800'
                    }`}
                  >
                    <span className="flex items-center gap-2">
                      <FileCode className="w-3.5 h-3.5 text-slate-400" />
                      <span>{file.name}</span>
                    </span>
                    <span className="text-[10px] uppercase text-slate-500">{file.type}</span>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
